FROM golang:1.25.1 as builder

ARG CGO_ENABLED=0

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o generator ./cmd/generator/main.go 

FROM scratch
COPY --from=builder /app/generator /generator

ENTRYPOINT ["/generator"]
CMD ["--url", "http://calculator_server:8080/api/v1/calc"]