FROM golang:1.25.1 AS builder

ARG CGO_ENABLED=1
ENV CGO_ENABLED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc libc6-dev curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable --profile minimal

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN chmod +x build.sh && ./build.sh

RUN go build -o calculator ./cmd/calculator/main.go

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/calculator                   /calculator
COPY --from=builder /app/include/libcalculator.so     /libcalculator.so
COPY --from=builder /app/include/libcalculator_rust.so /libcalculator_rust.so

COPY ./configs ./configs
EXPOSE 8080

ENTRYPOINT ["/calculator"]
CMD ["--config", "configs/config.yml"]